trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Web/Web.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'src/Web/Web.csproj'
    arguments: '--configuration ${buildConfiguration} --output ${Build.ArtifactStagingDirectory}/myapp'

- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'myapp'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '${Build.ArtifactStagingDirectory}/myapp'
    ArtifactName: 'myapp'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ServiceConnection'
    appName: 'eShopOnWeb'
    package: '$(Build.ArtifactStagingDirectory)/myapp'
    appType: 'webApp'
    deploymentMethod: 'zipDeploy'